version: '3.8'

services:
  ragheat-testing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragheat-testing-framework
    environment:
      - HEADLESS=true
      - RAGHEAT_FRONTEND_URL=http://ragheat-frontend:3000
      - RAGHEAT_API_URL=http://ragheat-backend:8000
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    networks:
      - ragheat-network
    depends_on:
      - ragheat-frontend
      - ragheat-backend
    command: python run_tests.py --suite all --headless true --check-app

  ragheat-frontend:
    image: node:18-alpine
    container_name: ragheat-frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    networks:
      - ragheat-network
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://ragheat-backend:8000

  ragheat-backend:
    image: python:3.11-slim
    container_name: ragheat-backend
    working_dir: /app
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - ragheat-network
    environment:
      - PYTHONPATH=/app
    command: sh -c "pip install -r requirements.txt && python simple_main.py"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: ragheat-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins:/var/jenkins_home/workspace
    networks:
      - ragheat-network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root

  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - ragheat-network

  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - ragheat-network

  test-reporter:
    image: nginx:alpine
    container_name: test-reporter
    ports:
      - "8888:80"
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
      - ./nginx-reports.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ragheat-network
    depends_on:
      - ragheat-testing

networks:
  ragheat-network:
    driver: bridge

volumes:
  jenkins_home: